In [28]:
#Importamos las librerias que queremos usar
import pandas as pd
#Es una libreria para visualizar estadisticas basada en Matploitlib
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#Importamos nuestra libreria
import aspect_based_sentiment_analysis as adsa
import tf_keras as keras
import warnings
warnings.filterwarnings(action='ignore')

In [12]:
#Instanciamos el archivo que desamos leer
df =  pd.read_json("tweets_extraction (1).json")

In [40]:
#imprime algunas filas de nuestro archivo.
df

,id,texto,usuario,hashtags,fecha,retweets,favoritos
0,12116719578733158,#BrechaAnuario2019 | Con cañón y coronel El vo...,SemanarioBrecha,"[BrechaAnuario2019, RelecturasDeUnAñoPerturbador]",2021-12-30T15:34:41.000Z,3,2
1,12116547084876964,"#BrechaAnuario2019 | Las PASO en Argentina ""Em...",SemanarioBrecha,[BrechaAnuario2019],2021-12-30T14:26:08.000Z,2,1
2,12116529643744992,#BrechaAnuario2019 | Bolsonaro contra la selva...,SemanarioBrecha,[BrechaAnuario2019],2021-12-30T14:19:12.000Z,3,2
3,12110290516301292,"#BrechaAnuario2019 | Aquí, los temas que apare...",SemanarioBrecha,"[BrechaAnuario2019, RelecturasDeUnAñoPerturbador]",2021-12-28T21:00:00.000Z,2,5
4,12107119614801142,#BrechaAnuario2019 | El mejor dibujante de his...,SemanarioBrecha,[BrechaAnuario2019],2021-12-28T00:00:00.000Z,0,4
...,...,...,...,...,...,...,...
290601,1080102594054406,Felicidades en este 1 dia del 2019. A todos l...,larepublica_uy,[],2021-01-01T14:05:00.000Z,11,32
290602,10800857075935356,Apareció flotando en una laguna el cuerpo del ...,larepublica_uy,[],2021-01-01T12:57:54.000Z,1,1
290603,1080077600553427,Recluso de Santiago Vázquez no retornó de una ...,larepublica_uy,[],2021-01-01T12:25:41.000Z,1,1
290604,1079905091438682,Volcán de Indonesia que desató el tsunami perd...,larepublica_uy,[],2021-01-01T01:00:12.000Z,0,0
290605,10798902581903892,La economía mundial se frenará en 2019 https:/...,larepublica_uy,[],2021-01-01T00:01:15.000Z,1,1

In [5]:
#Nos indica cuantas filas y columnas tiene nuestro archivo.
df.shape

(290606, 7)

In [6]:
#Nos ofrece un resumen estadistico, el cual incluye la contabilidad de las filas y columnas, una mediana, un estandar ...etc.
df.describe()

                 id       retweets      favoritos
count  2.906060e+05  290606.000000  290606.000000
mean   8.528872e+15       5.228137      13.255759
std    5.462012e+15      21.411017      55.577193
min    1.363557e+10       0.000000       0.000000
25%    1.286354e+15       0.000000       2.000000
50%    1.158710e+16       2.000000       4.000000
75%    1.276958e+16       4.000000       9.000000
max    1.396736e+16    2600.000000    7200.000000

In [41]:
#Nos trae los primeros 5 datos o items en nuestro archivo.
df.head()

,id,texto,usuario,hashtags,fecha,retweets,favoritos
0,12116719578733158,#BrechaAnuario2019 | Con cañón y coronel El vo...,SemanarioBrecha,"[BrechaAnuario2019, RelecturasDeUnAñoPerturbador]",2021-12-30T15:34:41.000Z,3,2
1,12116547084876964,"#BrechaAnuario2019 | Las PASO en Argentina ""Em...",SemanarioBrecha,[BrechaAnuario2019],2021-12-30T14:26:08.000Z,2,1
2,12116529643744992,#BrechaAnuario2019 | Bolsonaro contra la selva...,SemanarioBrecha,[BrechaAnuario2019],2021-12-30T14:19:12.000Z,3,2
3,12110290516301292,"#BrechaAnuario2019 | Aquí, los temas que apare...",SemanarioBrecha,"[BrechaAnuario2019, RelecturasDeUnAñoPerturbador]",2021-12-28T21:00:00.000Z,2,5
4,12107119614801142,#BrechaAnuario2019 | El mejor dibujante de his...,SemanarioBrecha,[BrechaAnuario2019],2021-12-28T00:00:00.000Z,0,4

In [42]:
#Nos trae los ultimos 5 datos o items de nuestro archivo
df.tail()

,id,texto,usuario,hashtags,fecha,retweets,favoritos
290601,1080102594054406,Felicidades en este 1 dia del 2019. A todos l...,larepublica_uy,[],2021-01-01T14:05:00.000Z,11,32
290602,10800857075935356,Apareció flotando en una laguna el cuerpo del ...,larepublica_uy,[],2021-01-01T12:57:54.000Z,1,1
290603,1080077600553427,Recluso de Santiago Vázquez no retornó de una ...,larepublica_uy,[],2021-01-01T12:25:41.000Z,1,1
290604,1079905091438682,Volcán de Indonesia que desató el tsunami perd...,larepublica_uy,[],2021-01-01T01:00:12.000Z,0,0
290605,10798902581903892,La economía mundial se frenará en 2019 https:/...,larepublica_uy,[],2021-01-01T00:01:15.000Z,1,1

In [43]:
#Para decirlo de una forma mas comprensible para todos 
#nos indica el titulo de las columnas que tiene nuestro archivo.
df.columns

Index(['id', 'texto', 'usuario', 'hashtags', 'fecha', 'retweets', 'favoritos'], dtype='object')

In [45]:
#Nos indica los tipos de datos que se encuentran en nuestras columnas.
df.dtypes

id            int64
texto        object
usuario      object
hashtags     object
fecha        object
retweets      int64
favoritos     int64
dtype: object

In [46]:
df.select_dtypes(include=['int64','object']).dtypes

id            int64
texto        object
usuario      object
hashtags     object
fecha        object
retweets      int64
favoritos     int64
dtype: object